#!/bin/sh

#  Script.sh
#  mach-exception
#
#  Created by Patrick Gili on 1/9/23.
#  
/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Script-4292215115026415848.sh (in target 'mach-exception-helper' from project 'mach-exception')
    cd /Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export ACTION\=build
    export AD_HOC_CODE_SIGNING_ALLOWED\=YES
    export ALLOW_TARGET_PLATFORM_SPECIALIZATION\=NO
    export ALTERNATE_GROUP\=staff
    export ALTERNATE_MODE\=u+w,go-w,a+rX
    export ALTERNATE_OWNER\=patrick
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES\=NO
    export ALWAYS_SEARCH_USER_PATHS\=YES
    export ALWAYS_USE_SEPARATE_HEADERMAPS\=NO
    export APPLE_INTERNAL_DEVELOPER_DIR\=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR\=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR\=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR\=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS\=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY\=NO
    export APPLY_RULES_IN_COPY_FILES\=NO
    export APPLY_RULES_IN_COPY_HEADERS\=NO
    export ARCHS\=arm64
    export ARCHS_STANDARD\=arm64\ x86_64
    export ARCHS_STANDARD_32_64_BIT\=arm64\ x86_64\ i386
    export ARCHS_STANDARD_32_BIT\=i386
    export ARCHS_STANDARD_64_BIT\=arm64\ x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT\=arm64\ x86_64
    export AVAILABLE_PLATFORMS\=appletvos\ appletvsimulator\ driverkit\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
    export BITCODE_GENERATION_MODE\=marker
    export BUILD_ACTIVE_RESOURCES_ONLY\=NO
    export BUILD_COMPONENTS\=headers\ build
    export BUILD_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products
    export BUILD_LIBRARY_FOR_DISTRIBUTION\=NO
    export BUILD_ROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products
    export BUILD_STYLE\=
    export BUILD_VARIANTS\=normal
    export BUILT_PRODUCTS_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug
    export BUNDLE_CONTENTS_FOLDER_PATH\=Contents/
    export BUNDLE_CONTENTS_FOLDER_PATH_deep\=Contents/
    export BUNDLE_EXECUTABLE_FOLDER_NAME_deep\=MacOS
    export BUNDLE_EXECUTABLE_FOLDER_PATH\=Contents/MacOS
    export BUNDLE_EXTENSIONS_FOLDER_PATH\=Contents/Extensions
    export BUNDLE_FORMAT\=deep
    export BUNDLE_FRAMEWORKS_FOLDER_PATH\=Contents/Frameworks
    export BUNDLE_PLUGINS_FOLDER_PATH\=Contents/PlugIns
    export BUNDLE_PRIVATE_HEADERS_FOLDER_PATH\=Contents/PrivateHeaders
    export BUNDLE_PUBLIC_HEADERS_FOLDER_PATH\=Contents/Headers
    export CACHE_ROOT\=/var/folders/nk/fnhnwzw10jxf_mcshtl9psvm0000gn/C/com.apple.DeveloperTools/14.2-14C18/Xcode
    export CCHROOT\=/var/folders/nk/fnhnwzw10jxf_mcshtl9psvm0000gn/C/com.apple.DeveloperTools/14.2-14C18/Xcode
    export CHMOD\=/bin/chmod
    export CHOWN\=/usr/sbin/chown
    export CLANG_COVERAGE_MAPPING\=YES
    export CLANG_COVERAGE_MAPPING_LINKER_ARGS\=NO
    export CLANG_ENABLE_MODULES\=YES
    export CLANG_ENABLE_OBJC_ARC\=YES
    export CLANG_MODULES_BUILD_SESSION_FILE\=/Users/patrick/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation
    export CLANG_PROFILE_DATA_DIRECTORY\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/ProfileData
    export CLASS_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/JavaClasses
    export CLEAN_PRECOMPS\=YES
    export CLONE_HEADERS\=NO
    export CODESIGNING_FOLDER_PATH\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug/mach-exception-helper.o
    export CODE_SIGNING_ALLOWED\=NO
    export CODE_SIGNING_REQUIRED\=NO
    export CODE_SIGN_IDENTITY_NO\=Apple\ Development
    export CODE_SIGN_IDENTITY_YES\=-
    export CODE_SIGN_INJECT_BASE_ENTITLEMENTS\=YES
    export COLOR_DIAGNOSTICS\=NO
    export COMBINE_HIDPI_IMAGES\=NO
    export COMPILER_INDEX_STORE_ENABLE\=Default
    export COMPOSITE_SDK_DIRS\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/CompositeSDKs
    export COMPRESS_PNG_FILES\=NO
    export CONFIGURATION\=Debug
    export CONFIGURATION_BUILD_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug
    export CONFIGURATION_TEMP_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug
    export COPYING_PRESERVES_HFS_DATA\=NO
    export COPY_HEADERS_RUN_UNIFDEF\=NO
    export COPY_PHASE_STRIP\=NO
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS\=YES
    export CP\=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY\=NO
    export CURRENT_ARCH\=undefined_arch
    export CURRENT_VARIANT\=normal
    export DEAD_CODE_STRIPPING\=NO
    export DEBUGGING_SYMBOLS\=YES
    export DEBUG_INFORMATION_FORMAT\=dwarf
    export DEFAULT_COMPILER\=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export DEFAULT_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export DEFINES_MODULE\=YES
    export DEPLOYMENT_LOCATION\=NO
    export DEPLOYMENT_POSTPROCESSING\=NO
    export DEPLOYMENT_TARGET_SETTING_NAME\=MACOSX_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_SUGGESTED_VALUES\=10.13\ 10.14\ 10.15\ 11.0\ 11.1\ 11.2\ 11.3\ 11.4\ 11.5\ 12.0\ 12.2\ 12.3\ 12.4\ 13.0\ 13.1
    export DERIVED_FILES_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/DerivedSources
    export DERIVED_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/DerivedSources
    export DERIVED_SOURCES_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED\=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE\=en
    export DONT_GENERATE_INFOPLIST_FILE\=NO
    export DO_HEADER_SCANNING_IN_JAM\=NO
    export DSTROOT\=/tmp/mach-exception.dst
    export DT_TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME\=mach-exception-helper.o.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT\=NO
    export DWARF_DSYM_FOLDER_PATH\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug
    export DYLIB_INSTALL_NAME_BASE\=@rpath
    export DYNAMIC_LIBRARY_EXTENSION\=dylib
    export EAGER_LINKING\=NO
    export EMBEDDED_CONTENT_CONTAINS_SWIFT\=NO
    export EMBEDDED_PROFILE_NAME\=embedded.provisionprofile
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE\=NO
    export ENABLE_APP_SANDBOX\=NO
    export ENABLE_BITCODE\=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS\=YES
    export ENABLE_DEFAULT_SEARCH_PATHS\=YES
    export ENABLE_HARDENED_RUNTIME\=NO
    export ENABLE_HEADER_DEPENDENCIES\=YES
    export ENABLE_NS_ASSERTIONS\=YES
    export ENABLE_ON_DEMAND_RESOURCES\=NO
    export ENABLE_PREVIEWS\=NO
    export ENABLE_TESTABILITY\=YES
    export ENABLE_TESTING_SEARCH_PATHS\=YES
    export ENABLE_USER_SCRIPT_SANDBOXING\=NO
    export ENTITLEMENTS_DESTINATION\=Signature
    export ENTITLEMENTS_REQUIRED\=NO
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS\=.DS_Store\ .svn\ .git\ .hg\ CVS
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES\=\*.nib\ \*.lproj\ \*.framework\ \*.gch\ \*.xcode\*\ \*.xcassets\ \(\*\)\ .DS_Store\ CVS\ .svn\ .git\ .hg\ \*.pbproj\ \*.pbxproj
    export EXECUTABLE_EXTENSION\=o
    export EXECUTABLE_NAME\=mach-exception-helper.o
    export EXECUTABLE_PATH\=mach-exception-helper.o
    export EXECUTABLE_SUFFIX\=.o
    export FILE_LIST\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects/LinkFileList
    export FIXED_FILES_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/FixedFiles
    export FRAMEWORK_FLAG_PREFIX\=-framework
    export FRAMEWORK_SEARCH_PATHS\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug\ \ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
    export FRAMEWORK_VERSION\=A
    export FULL_PRODUCT_NAME\=mach-exception-helper.o
    export FUSE_BUILD_PHASES\=YES
    export FUSE_BUILD_SCRIPT_PHASES\=NO
    export GCC3_VERSION\=3.3
    export GCC_INLINES_ARE_PRIVATE_EXTERN\=YES
    export GCC_OPTIMIZATION_LEVEL\=0
    export GCC_PFE_FILE_C_DIALECTS\=c\ objective-c\ c++\ objective-c++
    export GCC_PREPROCESSOR_DEFINITIONS\=\ SWIFT_PACKAGE\ DEBUG\=1
    export GCC_TREAT_WARNINGS_AS_ERRORS\=NO
    export GCC_VERSION\=com.apple.compilers.llvm.clang.1_0
    export GCC_VERSION_IDENTIFIER\=com_apple_compilers_llvm_clang_1_0
    export GCC_WARN_64_TO_32_BIT_CONVERSION\=NO
    export GENERATED_MODULEMAP_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/GeneratedModuleMaps
    export GENERATE_INFOPLIST_FILE\=NO
    export GENERATE_MASTER_OBJECT_FILE\=NO
    export GENERATE_PKGINFO_FILE\=NO
    export GENERATE_PROFILING_CODE\=NO
    export GENERATE_TEXT_BASED_STUBS\=NO
    export GID\=20
    export GROUP\=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT\=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES\=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS\=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS\=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES\=YES
    export HEADERMAP_USES_VFS\=YES
    export HEADER_SEARCH_PATHS\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug/include\ /Users/patrick/Documents/Apps/Swift\\\ Exception\\\ Handling/mach-exception/Sources/mach-exception-helper/include\
    export HIDE_BITCODE_SYMBOLS\=YES
    export HOME\=/Users/patrick
    export HOST_PLATFORM\=macosx
    export ICONV\=/usr/bin/iconv
    export INFOPLIST_EXPAND_BUILD_SETTINGS\=YES
    export INFOPLIST_OUTPUT_FORMAT\=same-as-input
    export INFOPLIST_PREPROCESS\=NO
    export INLINE_PRIVATE_FRAMEWORKS\=NO
    export INSTALLHDRS_COPY_PHASE\=NO
    export INSTALLHDRS_SCRIPT_PHASE\=NO
    export INSTALL_DIR\=/tmp/mach-exception.dst/Users/patrick/Objects
    export INSTALL_GROUP\=staff
    export INSTALL_MODE_FLAG\=u+w,go-w,a+rX
    export INSTALL_OWNER\=patrick
    export INSTALL_PATH\=/Users/patrick/Objects
    export INSTALL_ROOT\=/tmp/mach-exception.dst
    export IOS_UNZIPPERED_TWIN_PREFIX_PATH\=/System/iOSSupport
    export IS_MACCATALYST\=NO
    export IS_UIKITFORMAC\=NO
    export JAVAC_DEFAULT_FLAGS\=-J-Xms64m\ -J-XX:NewSize\=4M\ -J-Dfile.encoding\=UTF8
    export JAVA_APP_STUB\=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES\=YES
    export JAVA_ARCHIVE_TYPE\=JAR
    export JAVA_COMPILER\=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS\=Resources
    export JAVA_JAR_FLAGS\=cv
    export JAVA_SOURCE_SUBDIR\=.
    export JAVA_USE_DEPENDENCIES\=YES
    export JAVA_ZIP_FLAGS\=-urg
    export JIKES_DEFAULT_FLAGS\=+E\ +OLDCSO
    export KASAN_CFLAGS_CLASSIC\=-DKASAN\=1\ -DKASAN_CLASSIC\=1\ -fsanitize\=address\ -mllvm\ -asan-globals-live-support\ -mllvm\ -asan-force-dynamic-shadow
    export KASAN_CFLAGS_TBI\=-DKASAN\=1\ -DKASAN_TBI\=1\ -fsanitize\=kernel-hwaddress\ -mllvm\ -hwasan-recover\=0\ -mllvm\ -hwasan-instrument-atomics\=0\ -mllvm\ -hwasan-instrument-stack\=1\ -mllvm\ -hwasan-uar-retag-to-zero\=1\ -mllvm\ -hwasan-generate-tags-with-calls\=1\ -mllvm\ -hwasan-instrument-with-calls\=1\ -mllvm\ -hwasan-use-short-granules\=0\ \ -mllvm\ -hwasan-memory-access-callback-prefix\=__asan_
    export KASAN_DEFAULT_CFLAGS\=-DKASAN\=1\ -DKASAN_CLASSIC\=1\ -fsanitize\=address\ -mllvm\ -asan-globals-live-support\ -mllvm\ -asan-force-dynamic-shadow
    export KEEP_PRIVATE_EXTERNS\=NO
    export LD_DEPENDENCY_INFO_FILE\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal/undefined_arch/mach-exception-helper_dependency_info.dat
    export LD_GENERATE_MAP_FILE\=NO
    export LD_MAP_FILE_PATH\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/mach-exception-helper-LinkMap-normal-undefined_arch.txt
    export LD_NO_PIE\=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER\=YES
    export LEGACY_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LEX\=lex
    export LIBRARY_DEXT_INSTALL_PATH\=/Library/DriverExtensions
    export LIBRARY_FLAG_NOSPACE\=YES
    export LIBRARY_FLAG_PREFIX\=-l
    export LIBRARY_KEXT_INSTALL_PATH\=/Library/Extensions
    export LIBRARY_SEARCH_PATHS\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug\ \ \ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
    export LINKER_DISPLAYS_MANGLED_NAMES\=NO
    export LINK_FILE_LIST_normal_arm64\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal/arm64/mach-exception-helper.LinkFileList
    export LINK_OBJC_RUNTIME\=YES
    export LINK_WITH_STANDARD_LIBRARIES\=NO
    export LLVM_TARGET_TRIPLE_OS_VERSION\=macos12.0
    export LLVM_TARGET_TRIPLE_OS_VERSION_NO\=macos12.0
    export LLVM_TARGET_TRIPLE_OS_VERSION_YES\=macos13.1
    export LLVM_TARGET_TRIPLE_VENDOR\=apple
    export LOCALIZATION_EXPORT_SUPPORTED\=YES
    export LOCALIZED_STRING_MACRO_NAMES\=NSLocalizedString\ CFCopyLocalizedString
    export LOCALIZED_STRING_SWIFTUI_SUPPORT\=YES
    export LOCAL_ADMIN_APPS_DIR\=/Applications/Utilities
    export LOCAL_APPS_DIR\=/Applications
    export LOCAL_DEVELOPER_DIR\=/Library/Developer
    export LOCAL_LIBRARY_DIR\=/Library
    export LOCROOT\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export LOCSYMROOT\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export MACH_O_TYPE\=mh_object
    export MACOSX_DEPLOYMENT_TARGET\=12.0
    export MAC_OS_X_PRODUCT_BUILD_VERSION\=22C65
    export MAC_OS_X_VERSION_ACTUAL\=130100
    export MAC_OS_X_VERSION_MAJOR\=130000
    export MAC_OS_X_VERSION_MINOR\=130100
    export METAL_LIBRARY_FILE_BASE\=default
    export METAL_LIBRARY_OUTPUT_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug/
    export MODULEMAP_FILE_CONTENTS\=module\ mach_exception_helper\ \{'
'umbrella\ header\ \"/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception/Sources/mach-exception-helper/include/mach_exception_helper.h\"'
'export\ \*'
'\}
    export MODULEMAP_PATH\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/GeneratedModuleMaps/mach-exception-helper.modulemap
    export MODULE_CACHE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
    export NATIVE_ARCH\=arm64
    export NATIVE_ARCH_32_BIT\=arm
    export NATIVE_ARCH_64_BIT\=arm64
    export NATIVE_ARCH_ACTUAL\=arm64
    export NO_COMMON\=YES
    export OBJECT_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects
    export OBJECT_FILE_DIR_normal\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal
    export OBJROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex
    export ONLY_ACTIVE_ARCH\=YES
    export OS\=MACOS
    export OSAC\=/usr/bin/osacompile
    export OTHER_CFLAGS\=\ -DXcode
    export OTHER_CPLUSPLUSFLAGS\=\ -DXcode
    export OTHER_SWIFT_FLAGS\=\ -DXcode
    export PACKAGE_RESOURCE_TARGET_KIND\=regular
    export PACKAGE_TYPE\=com.apple.package-type.mach-o-objfile
    export PASCAL_STRINGS\=YES
    export PATH\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/appleinternal/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/appleinternal/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES\=/usr/include\ /usr/local/include\ /System/Library/Frameworks\ /System/Library/PrivateFrameworks\ /Applications/Xcode.app/Contents/Developer/Headers\ /Applications/Xcode.app/Contents/Developer/SDKs\ /Applications/Xcode.app/Contents/Developer/Platforms
    export PER_ARCH_OBJECT_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal/undefined_arch
    export PER_VARIANT_OBJECT_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal
    export PKGINFO_FILE_PATH\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/PkgInfo
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR\=/Applications/Xcode.app/Contents/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export PLATFORM_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
    export PLATFORM_DISPLAY_NAME\=macOS
    export PLATFORM_FAMILY_NAME\=macOS
    export PLATFORM_NAME\=macosx
    export PLATFORM_PREFERRED_ARCH\=x86_64
    export PLATFORM_PRODUCT_BUILD_VERSION\=14C18
    export PLIST_FILE_OUTPUT_FORMAT\=same-as-input
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR\=YES
    export PRECOMP_DESTINATION_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS\=NO
    export PRIVATE_HEADERS_FOLDER_PATH\=/usr/local/include
    export PRODUCT_BUNDLE_IDENTIFIER\=mach-exception-helper
    export PRODUCT_MODULE_NAME\=mach_exception_helper
    export PRODUCT_NAME\=mach-exception-helper
    export PRODUCT_SETTINGS_PATH\=
    export PRODUCT_TYPE\=com.apple.product-type.objfile
    export PROFILING_CODE\=NO
    export PROJECT\=mach-exception
    export PROJECT_DERIVED_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/DerivedSources
    export PROJECT_DIR\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export PROJECT_FILE_PATH\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception/Package.swift
    export PROJECT_NAME\=mach-exception
    export PROJECT_TEMP_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build
    export PROJECT_TEMP_ROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex
    export PUBLIC_HEADERS_FOLDER_PATH\=/usr/local/include
    export RECOMMENDED_MACOSX_DEPLOYMENT_TARGET\=10.14.6
    export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS\=YES
    export REMOVE_CVS_FROM_RESOURCES\=YES
    export REMOVE_GIT_FROM_RESOURCES\=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES\=YES
    export REMOVE_HG_FROM_RESOURCES\=YES
    export REMOVE_SVN_FROM_RESOURCES\=YES
    export REZ_COLLECTOR_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/ResourceManagerResources
    export REZ_EXECUTABLE\=YES
    export REZ_OBJECTS_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/ResourceManagerResources/Objects
    export REZ_SEARCH_PATHS\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug\
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES\=NO
    export SCRIPT_INPUT_FILE_0\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/mig
    export SCRIPT_INPUT_FILE_1\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception/Sources/mach-exception-helper/my.defs
    export SCRIPT_INPUT_FILE_COUNT\=2
    export SCRIPT_INPUT_FILE_LIST_COUNT\=0
    export SCRIPT_OUTPUT_FILE_0\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/SourcePackages/plugins/mach-exception.output/mach-exception-helper/MachInterfaceGenerator/myServer.c
    export SCRIPT_OUTPUT_FILE_1\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/SourcePackages/plugins/mach-exception.output/mach-exception-helper/MachInterfaceGenerator/myServer.h
    export SCRIPT_OUTPUT_FILE_COUNT\=2
    export SCRIPT_OUTPUT_FILE_LIST_COUNT\=0
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
    export SDK_DIR\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
    export SDK_DIR_macosx\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
    export SDK_DIR_macosx13_1\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
    export SDK_NAME\=macosx13.1
    export SDK_NAMES\=macosx13.1
    export SDK_PRODUCT_BUILD_VERSION\=22C55
    export SDK_VERSION\=13.1
    export SDK_VERSION_ACTUAL\=130100
    export SDK_VERSION_MAJOR\=130000
    export SDK_VERSION_MINOR\=130100
    export SED\=/usr/bin/sed
    export SEPARATE_STRIP\=NO
    export SEPARATE_SYMBOL_EDIT\=NO
    export SET_DIR_MODE_OWNER_GROUP\=YES
    export SET_FILE_MODE_OWNER_GROUP\=NO
    export SHALLOW_BUNDLE\=NO
    export SHARED_DERIVED_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug/DerivedSources
    export SHARED_PRECOMPS_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/PrecompiledHeaders
    export SKIP_INSTALL\=YES
    export SOURCE_ROOT\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export SRCROOT\=/Users/patrick/Documents/Apps/Swift\ Exception\ Handling/mach-exception
    export STRINGSDATA_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal/undefined_arch
    export STRINGSDATA_ROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build
    export STRINGS_FILE_INFOPLIST_RENAME\=YES
    export STRINGS_FILE_OUTPUT_ENCODING\=UTF-16
    export STRIP_BITCODE_FROM_COPIED_FILES\=NO
    export STRIP_INSTALLED_PRODUCT\=NO
    export STRIP_PNG_TEXT\=NO
    export STRIP_STYLE\=debugging
    export STRIP_SWIFT_SYMBOLS\=YES
    export SUPPORTED_PLATFORMS\=appletvos\ appletvsimulator\ driverkit\ iphoneos\ iphonesimulator\ macosx\ watchos\ watchsimulator
    export SUPPORTS_TEXT_BASED_API\=NO
    export SWIFT_ACTIVE_COMPILATION_CONDITIONS\=\ SWIFT_PACKAGE\ DEBUG
    export SWIFT_EMIT_LOC_STRINGS\=NO
    export SWIFT_ENABLE_BARE_SLASH_REGEX\=NO
    export SWIFT_INSTALL_OBJC_HEADER\=NO
    export SWIFT_OPTIMIZATION_LEVEL\=-Onone
    export SWIFT_PLATFORM_TARGET_PREFIX\=macos
    export SWIFT_RESPONSE_FILE_PATH_normal_arm64\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Objects-normal/arm64/mach-exception-helper.SwiftFileList
    export SYMROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products
    export SYSTEM_ADMIN_APPS_DIR\=/Applications/Utilities
    export SYSTEM_APPS_DIR\=/Applications
    export SYSTEM_CORE_SERVICES_DIR\=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR\=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR\=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built\ Examples
    export SYSTEM_DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Graphics\ Tools
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Java\ Tools
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Performance\ Tools
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes
    export SYSTEM_DEVELOPER_TOOLS\=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/documentation/DeveloperTools
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR\=/Applications/Xcode.app/Contents/Developer/ADC\ Reference\ Library/releasenotes/DeveloperTools
    export SYSTEM_DEVELOPER_USR_DIR\=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR\=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DEXT_INSTALL_PATH\=/System/Library/DriverExtensions
    export SYSTEM_DOCUMENTATION_DIR\=/Library/Documentation
    export SYSTEM_FRAMEWORK_SEARCH_PATHS\=\ \ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
    export SYSTEM_KEXT_INSTALL_PATH\=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR\=/System/Library
    export TAPI_DYLIB_INSTALL_NAME\=mach-exception-helper
    export TAPI_ENABLE_PROJECT_HEADERS\=NO
    export TAPI_VERIFY_MODE\=ErrorsOnly
    export TARGETED_DEVICE_FAMILY\=1,2,3,4,6
    export TARGETNAME\=mach-exception-helper
    export TARGET_BUILD_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Products/Debug
    export TARGET_NAME\=mach-exception-helper
    export TARGET_TEMP_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build
    export TEMP_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build
    export TEMP_FILES_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build
    export TEMP_FILE_DIR\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build
    export TEMP_ROOT\=/Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex
    export TEST_FRAMEWORK_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
    export TEST_LIBRARY_SEARCH_PATHS\=\ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
    export TOOLCHAINS\=com.apple.dt.toolchain.XcodeDefault
    export TOOLCHAIN_DIR\=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES\=NO
    export UID\=501
    export UNSTRIPPED_PRODUCT\=NO
    export USER\=patrick
    export USER_APPS_DIR\=/Users/patrick/Applications
    export USER_LIBRARY_DIR\=/Users/patrick/Library
    export USE_DYNAMIC_NO_PIC\=YES
    export USE_HEADERMAP\=NO
    export USE_HEADER_SYMLINKS\=NO
    export USE_LLVM_TARGET_TRIPLES\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_CLANG\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_LD\=YES
    export USE_LLVM_TARGET_TRIPLES_FOR_TAPI\=YES
    export VALIDATE_DEVELOPMENT_ASSET_PATHS\=YES_ERROR
    export VALIDATE_PRODUCT\=NO
    export VALID_ARCHS\=arm64\ arm64e\ i386\ x86_64
    export VERBOSE_PBXCP\=NO
    export VERSION_INFO_BUILDER\=patrick
    export VERSION_INFO_FILE\=mach-exception-helper_vers.c
    export VERSION_INFO_STRING\=\"@\(\#\)PROGRAM:mach-exception-helper\ \ PROJECT:mach-exception-\"
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES\=NO
    export XCODE_APP_SUPPORT_DIR\=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION\=14C18
    export XCODE_VERSION_ACTUAL\=1420
    export XCODE_VERSION_MAJOR\=1400
    export XCODE_VERSION_MINOR\=1420
    export XPCSERVICES_FOLDER_PATH\=/XPCServices
    export YACC\=yacc
    export _BOOL_\=NO
    export _BOOL_NO\=NO
    export _BOOL_YES\=YES
    export _DEVELOPMENT_TEAM_IS_EMPTY\=YES
    export _IS_EMPTY_\=YES
    export _MACOSX_DEPLOYMENT_TARGET_IS_EMPTY\=NO
    export arch\=undefined_arch
    export variant\=normal
    /bin/sh -c /Users/patrick/Library/Developer/Xcode/DerivedData/mach-exception-bpvrroqrbftldofiudkctkdmqylw/Build/Intermediates.noindex/mach-exception.build/Debug/mach-exception-helper.build/Script-4292215115026415848.sh

